# Generated by Django 5.2.5 on 2025-08-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('room', models.CharField(max_length=10, verbose_name='Палата')),
                ('admission_date', models.DateField(verbose_name='Дата поступления')),
            ],
        ),
    ]
