# Generated by Django 5.2.5 on 2025-08-17 13:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-admission_date', 'room'], 'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='Аллергии'),
        ),
        migrations.AddField(
            model_name='patient',
            name='attending_physician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.doctor', verbose_name='Лечащий врач'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default=1, max_length=3, verbose_name='Группа крови'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True, null=True, verbose_name='Хронические заболевания'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medication',
            field=models.TextField(blank=True, null=True, verbose_name='Текущие лекарства'),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharge_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выписки'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default=1, max_length=1, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Страховой номер'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(choices=[('in_treatment', 'На лечении'), ('discharged', 'Выписан'), ('transferred', 'Переведен'), ('deceased', 'Умер')], default='in_treatment', max_length=20, verbose_name='Статус пациента'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.TextField(verbose_name='Основной диагноз'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='room',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Палата'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('result_file', models.FileField(upload_to='test_results/')),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
