# Generated by Django 5.2.5 on 2025-08-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='doctors/')),
                ('qualification', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='nurses/')),
            ],
        ),
    ]
