# Generated by Django 5.2.5 on 2025-08-14 19:59

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('core', '0005_alter_user_phone'),
        ('medications', '0004_alter_medication_responsible_nurse'),
        ('prescriptions', '0002_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
