# Generated by Django 5.2.5 on 2025-08-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('dosage', models.CharField(max_length=50, verbose_name='Дозировка')),
                ('stock', models.IntegerField(verbose_name='Остаток')),
                ('critical_level', models.IntegerField(default=10, verbose_name='Критический остаток')),
            ],
        ),
    ]
