# Generated by Django 5.2.5 on 2025-08-12 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='critical_level',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='stock',
        ),
        migrations.AddField(
            model_name='medication',
            name='responsible_nurse',
            field=models.ForeignKey(limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
