# Generated by Django 5.2.5 on 2025-08-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_groups_and_more'),
        ('medications', '0002_remove_medication_critical_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='critical_level',
            field=models.IntegerField(default=10, verbose_name='Критический остаток'),
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дозировка'),
        ),
        migrations.AddField(
            model_name='medication',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Остаток'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='responsible_nurse',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='Ответственная медсестра'),
        ),
    ]
