# Generated by Django 5.2.5 on 2025-08-12 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('status', models.CharField(choices=[('assigned', 'Назначено'), ('in_progress', 'В работе'), ('done', 'Выполнено')], max_length=20, verbose_name='Статус')),
                ('due_time', models.DateTimeField(verbose_name='Срок выполнения')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
